rahataid/rahat-platform-nx

- apps/beneficiary/src/beneficiary/beneficiary.controller.ts
- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- libs/sdk/src/beneficiary/beneficiary.events.ts
- libs/sdk/src/constants/index.ts
Description:
-Added new action to list pii data(details ) of referred beneficiary.
-Listens command of project microservice to fetch the details of beneficiary.
> Referredben details

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- libs/extensions/src/dtos/beneficiary/create-beneficiary.dto.ts
- libs/sdk/src/index.ts
- libs/sdk/src/utils/index.ts
- libs/sdk/src/utils/wallet-generator.ts
- package.json
- pnpm-lock.yaml
This update introduces significant enhancements to the Beneficiary Service, focusing on the automatic generation of wallet addresses. Key changes include:
Automatic Wallet Address Generation: For new beneficiaries without a specified wallet address, the service now automatically generates a wallet address using the generateWallet function, leveraging the beneficiary's phone number as input. This ensures that all beneficiaries have a wallet address without manual intervention.
Fallback Wallet Address Generation: During bulk operations where beneficiaries might not have a wallet address, the service now uses the generateRandomWallet function as a fallback to generate wallet addresses. This ensures consistency and completeness of beneficiary data.
Code Refinement: Minor code refinements …
> Generate wallet address

- libs/extensions/src/dtos/beneficiary/add.beneficiary.project.dto.ts
- libs/extensions/src/dtos/beneficiary/create-beneficiary.dto.ts
- libs/sdk/src/beneficiary/beneficiary.types.ts
- prisma/migrations/20240403114455_ben_address/migration.sql
- prisma/schema.prisma
Description:
- Updated beneficiary scheme(added ageRange as a optional field, made walletAddress phone number unique)
- Updated dtos according to change in scheme.
> Update ben scheme

- apps/rahat/src/projects/project.service.ts
- libs/sdk/src/constants/index.ts
- Separate service created for el specific meta transaction and database updates.
> Action Temp fixes

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- filter PII data based on project uuid
> fix:filter pi data based on project uuid

- package.json
- updated extension
- updated version fix type issue in user
> fix:updated extension

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- apps/rahat/src/beneficiary/beneficiary.controller.ts
- project based filter API
- beneficiary type base filter
https://github.com/rahataid/rahat-ui/issues/313
> fix:project based filter

- apps/rahat/src/projects/project.service.ts
- fixes in microservice action
> action : Fixes metatx

- apps/rahat/src/listeners/listeners.module.ts
- apps/rahat/src/listeners/listeners.service.ts
- apps/rahat/src/listeners/messageSender.service.ts
- apps/rahat/src/projects/project.service.ts
- libs/sdk/src/project/project.events.ts
- send whatsapp message on voucher redemption
> fix:send message on voucher redemption

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- apps/rahat/src/projects/actions/el.action.ts
Added project action for project stats.
> Project action changes

- apps/rahat/src/projects/actions/aa.action.ts
- apps/rahat/src/projects/project.controller.ts
- apps/rahat/src/projects/project.service.ts
- libs/sdk/src/aa/aa.events.ts
- libs/sdk/src/constants/index.ts
This update introduces significant enhancements and refactoring to the project actions within the Rahat application. The key changes include:
1. **Refactoring of Schedule to Triggers**: The `SCHEDULE` actions have been renamed to `TRIGGERS`, reflecting a broader scope of functionality. This change affects both the action constants and the corresponding job commands across the application, enhancing clarity and expanding the potential use cases of these triggers.
2. **Introduction of Communication Actions**: New actions related to communication have been added, including `ADD` and `TRIGGER` communication events. This enhancement allows for more sophisticated communication workflows within projects, facilitating better interaction and notification mechanisms.
3. **Expansion of Stakeholder …
> AA: Project Actions 

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- apps/rahat/src/projects/project.service.ts
- apps/rahat/src/utils/fileUpload.ts
- apps/rahat/src/utils/qrGenerator.ts
- package.json
- pnpm-lock.yaml
- generate qr code from walletaddress
- save qr buffer to s3
- use s3 url to create twilio whatsapp template
- submit template for approval
> fix:save qr and send for approval

- apps/rahat/src/beneficiary/beneficiary.controller.ts
- apps/rahat/src/listeners/listeners.service.ts
- apps/rahat/src/projects/project.service.ts
- libs/sdk/src/constants/index.ts
Add new action to send whatsapp message after sucessful otp claim
> Action: Otp sucess

- apps/rahat/src/projects/actions/aa.action.ts
- libs/sdk/src/aa/aa.events.ts
- libs/sdk/src/constants/index.ts
- aa action for communication logs
> fix:aa action for communication logs

- apps/beneficiary/src/beneficiary/beneficiary.service.ts
- apps/beneficiary/src/vendors/vendors.service.ts
- libs/extensions/src/dtos/beneficiary/list-beneficiary.dto.ts
Send query as startDate = and endDate =
Results will be filtered between this dates.
> Date filter added for audinece

- apps/rahat/src/projects/actions/rp.action.ts
- libs/sdk/src/constants/index.ts
- libs/sdk/src/project/project.events.ts
- added actions for rp campaigns
> fix:added rp actions

- apps/rahat/src/projects/actions/rp.action.ts
- added actions to get all transport
> fix:added action to list transport

- apps/rahat/src/projects/actions/c2c.action.ts
- apps/rahat/src/projects/actions/cva.action.ts
- libs/sdk/src/constants/index.ts
- added campaign actions for c2c and cva projects
> fix:added campaign actions for projects

- apps/graph/networks.json
- apps/graph/subgraph.yaml
- apps/rahat/src/beneficiary/beneficiary.controller.ts
- apps/rahat/src/projects/actions/rp.action.ts
- libs/sdk/src/constants/index.ts
- libs/sdk/src/project/project.events.ts
- pnpm-lock.yaml
- tools/scripts/local-setup/web3_setup/deployments/contracts.json
> Offline sync

- apps/rahat/src/projects/actions/rp.action.ts
- libs/sdk/src/beneficiary/beneficiary.events.ts
- libs/sdk/src/constants/index.ts
- libs/sdk/src/project/project.events.ts
- actions to add,get and list benficiary groups
- action to get disbursements from group id
> action for beneficiary groups
